"""Admin slash commands for webhook security (token + IP allowlist).

Kept separate from the timetracking cog because the webhook server runs
regardless of whether timetracking is enabled.
"""

import discord
from discord.ext import commands

import config
from botlog import log
from cogs.timetracking.perms import is_timecard_admin


class WebhookAdmin(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @discord.slash_command(
        name="regenwebhooktoken",
        description="Rotate the inbound webhook token (if you think it's compromised).",
    )
    @is_timecard_admin()
    async def regenwebhooktoken(self, ctx: discord.ApplicationContext):
        config.regenerate_webhook_token()
        log.warning("[Webhook] Token regenerated by %s.", ctx.author)
        # Deliberately NOT sending the token to Discord.
        await ctx.respond(
            "🔑 Webhook token **regenerated**. For security it is not shown here — "
            "read the new `WEBHOOK_TOKEN` from the server's `.env` file, then update the "
            "`?token=` value in your Odoo automation URLs.",
            ephemeral=True,
        )

    @discord.slash_command(
        name="webhookallowlist",
        description="Enable/disable or inspect the webhook IP allowlist.",
    )
    @is_timecard_admin()
    async def webhookallowlist(
        self, ctx: discord.ApplicationContext,
        action: discord.Option(str, description="What to do", choices=["enable", "disable", "status"]),  # type: ignore
    ):
        if action == "enable":
            config.set_ip_allowlist_enabled(True)
            allow = config.get_ip_allowlist()
            log.warning("[Webhook] IP allowlist ENABLED by %s.", ctx.author)
            note = "" if allow else " ⚠️ The allowlist is currently empty — it fills in the next time the bot calls Odoo."
            await ctx.respond(f"✅ Webhook IP allowlist **enabled**.{note}", ephemeral=True)
        elif action == "disable":
            config.set_ip_allowlist_enabled(False)
            log.warning("[Webhook] IP allowlist DISABLED by %s.", ctx.author)
            await ctx.respond("✅ Webhook IP allowlist **disabled** (token is still enforced).", ephemeral=True)
        else:  # status
            enabled = config.ip_allowlist_enabled()
            allow = sorted(config.get_ip_allowlist())
            body = ", ".join(f"`{ip}`" for ip in allow) if allow else "_(empty)_"
            await ctx.respond(
                f"Webhook IP allowlist is **{'enabled' if enabled else 'disabled'}**.\nKnown IPs: {body}",
                ephemeral=True,
            )


def setup(bot):
    bot.add_cog(WebhookAdmin(bot))
